<?php 
	session_start();
	error_reporting(0);
?>
<!DOCTYPE html>
<html class="no-js">
	<head>
		<title>Typing Finga</title>
		<meta name="keywords" content="typing,practice,free typing,keyboard,desktop practice">
		<meta name="description" content="Free Typing Practice">
		<meta name="author" content="Abhishek Mashetty">
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="theme-color" content="#ff0000" >
		<link rel="icon"  href="css/t.png">
		<!--<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">-->
		<link rel="stylesheet" href="css/w3_css.css">
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Oswald">
		<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open Sans">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.min.js"></script>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js"></script>
		<script src="http://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.2/modernizr.js"></script>
		<script>
			//paste this code under head tag or in a seperate js file.
			// Wait for window load
			$(window).load(function() {
			// Animate loader off screen
			$(".se-pre-con").fadeOut("slow");;
			});
		</script>
	<style>
		h1,h2,h3,h4,h5,h6 {font-family: "Oswald"}
		body {font-family: "Open Sans"}
		.no-js #loader { display: none;  }
		.js #loader { display: block; position: absolute; left: 100px; top: 0; }
		.se-pre-con {
			position: fixed;
			left: 0px;
			top: 0px;
			width: 100%;
			height: 100%;
			z-index: 9999;
			background: url(css/puff.svg) center no-repeat gray;
		}
	</style>
	</head>
<body class="w3-light-grey">

<!-- Navigation bar with social media icons -->
<div class="w3-bar w3-black ">
  <a href="https://www.facebook.com/abhimashetty" class="w3-bar-item w3-button"><i class="fa fa-facebook-official"></i></a>
  <a href="https://www.instagram.com/abhi_mashetty" class="w3-bar-item w3-button"><i class="fa fa-instagram"></i></a>
  <a href="https://www.youtube.com/channel/UCdT31xm9_1UNHbKd8qQM5gg" class="w3-bar-item w3-button"><i class="fa fa-youtube"></i></a>
  <a href="#" class="w3-bar-item w3-button"><i class="fa fa-flickr"></i></a>
  <a href="https://twitter.com/abhi_mashetty" class="w3-bar-item w3-button"><i class="fa fa-twitter"></i></a>
  <a href="https://www.linkedin.com/in/abhishek-mashetty-0b6265a4" class="w3-bar-item w3-button"><i class="fa fa-linkedin"></i></a>
  <a class="w3-bar-item w3-button w3-right " style="text-decoration:none"><?php echo "UserId  ".$_SESSION['Site_User']; ?></a>  
  <!--<a href="#" class="w3-bar-item w3-button w3-right"><i class="fa fa-search"></i></a>-->
</div>
  
<!-- w3-content defines a container for fixed size centered content, 
and is wrapped around the whole page content, except for the footer in this example -->
<div class="w3-content" style="max-width:1600px">

  <!-- Header -->
  <header class="w3-container w3-center w3-padding-48 w3-white w3-animate-opacity">
    <h1 class="w3-xxxlarge"><b>Typing Practice</b></h1>
    <h6>Welcome to the world of <span class="w3-tag w3-xlarge">Typing</span></h6>
  </header>

	<?php include"index_typing_basic.php" ?>
	<?php include"callback.php" ?>
  <!-- Grid -->
  <div class="w3-row w3-padding w3-border">

    <!-- Blog entries -->
    <div class="w3-col l8 s12">

      <!-- Blog entry -->
      <div class="w3-container w3-white w3-margin w3-padding-large">
        <div class="w3-center">
          <!--<h3>ABOUT YOU</h3>-->		
          <h5><span class="w3-opacity w3-wide"><?php 
			$mydate=getdate(date("U"));
			echo $mydate[month]," ", $mydate[mday],", ", $mydate[year]; ?></span></h5>
        </div>

        <div class="w3-justify" id="users_ip_details_with_many_other_things">
				<!-- Here The Ip Detail Table will be generated by callback.php file-->
        </div>
      </div>
      
    <!-- END BLOG ENTRIES -->
    </div>

    <!-- About/Information menu -->
    <div class="w3-col l4">
          

      <!-- Posts -->
      <div class="w3-white w3-margin">
        <div class="w3-container w3-padding w3-black">
          <h4>levels</h4>
        </div>
        <ul class="w3-ul w3-hoverable w3-white">
          <li class="w3-padding-16">
            <!--<img src="/w3images/avatar_smoke.jpg" alt="Image" class="w3-left w3-margin-right" style="width:50px">-->
			<i class="fa fa-cube w3-large w3-left w3-margin-right w3-hover-opacity"></i>
            <a href="index.php"><span class="w3-large w3-margin-left">Easy</span></a>
            <br>
            <!--<span>for beginners</span>-->
          </li>
          <li class="w3-padding-16">
            <!--<img src="/w3images/bandmember.jpg" alt="Image" class="w3-left w3-margin-right" style="width:50px">-->
			<i class="fa fa-cube w3-large w3-left w3-margin-right w3-hover-opacity"></i>
            <a href="index_intermediate.php"><span class="w3-large w3-margin-left">Intermediate</span></a>
            <br>
            <!--<span>for beginners</span>-->
          </li>
          <li class="w3-padding-16">
            <!--<img src="/w3images/workshop.jpg" alt="Image" class="w3-left w3-margin-right" style="width:50px">-->
			<i class="fa fa-cube w3-large w3-left w3-margin-right w3-hover-opacity"></i>
            <a href="index_difficult.php"><span class="w3-large w3-margin-left">Difficult</span></a>
            <br>
            <!--<span>for beginners</span>-->
          </li>
          <li class="w3-padding-16">
            <!--<img src="/w3images/avatar_smoke.jpg" alt="Image" class="w3-left w3-margin-right w3-sepia" style="width:50px">-->
			<i class="fa fa-cube w3-large w3-left w3-margin-right w3-hover-opacity"></i>
            <a href="index_pro.php"><span class="w3-large w3-margin-left">Pro</span></a>
            <br>
            <!--<span>for beginners</span>-->
          </li>
        </ul>
      </div>
      <hr>

      <div class="w3-white w3-margin">
        <div class="w3-container w3-padding w3-black">
          <h4>Follow On</h4>
        </div>
        <div class="w3-container w3-xlarge w3-padding">
			<a href="https://www.facebook.com/abhimashetty" class="w3-bar-item w3-button w3-hover-none"><i class="fa fa-facebook-official w3-hover-opacity"></i></a>
			<a href="https://www.instagram.com/abhi_mashetty" class="w3-bar-item w3-button w3-hover-none"><i class="fa fa-instagram w3-hover-opacity"></i></a>
			<a href="https://www.youtube.com/channel/UCdT31xm9_1UNHbKd8qQM5gg/" class="w3-bar-item w3-button w3-hover-none"><i class="fa fa-youtube w3-hover-opacity"></i></a>
			<a href="#" class="w3-bar-item w3-button w3-hover-none"><i class="fa fa-flickr w3-hover-opacity"></i></a>
			<a href="https://twitter.com/abhi_mashetty" class="w3-bar-item w3-button w3-hover-none"><i class="fa fa-twitter w3-hover-opacity"></i></a>
			<a href="https://www.linkedin.com/in/abhishek-mashetty-0b6265a4" class="w3-bar-item w3-button w3-hover-none"><i class="fa fa-linkedin w3-hover-opacity"></i></a>
        </div>
      </div>
      <hr>
      
      <!-- Subscribe -->
      <div class="w3-white w3-margin">
        <div class="w3-container w3-padding w3-black">
          <h4>Subscribe</h4>
        </div>
        <div class="w3-container w3-white"><br>
          <p>Enter your e-mail below and get notified for new challenges.</p>
		  <form method="POST" id="email_form">
			  <input class="w3-input w3-border" type="email" id="email_id" name="email" placeholder="Enter e-mail" style="width:100%" required>
			  <button type="button" form="email_form" onclick="user_entering_email_id()" class="w3-button w3-block w3-red w3-margin-bottom" value="SUBSCRIBE">SUBSCRIBE</button>
			  <br>
		  </form>
        </div>
      </div>

	  <script>
	  function user_entering_email_id(){
			var users_mail = document.getElementById("email_id").value;
			var validated_mail_id = ValidateEmail(users_mail);
			if(validated_mail_id){
				var xmlht = new XMLHttpRequest();
				xmlht.onreadystatechange = function() {
						if (xmlht.readyState == 4 && xmlht.status == 200) {
								var resp = JSON.parse(xmlht.responseText);
							}
				};
				xmlht.open("GET", "user_email.php?q="+users_mail, true);
				xmlht.send();	
				document.getElementById('get_back_soon').innerHTML="We will get back to you soon !!!";
				document.getElementById('thank_you_message').innerHTML="Thank you For Subscribing";
				document.getElementById('thank_you_message').style.display='block';
				document.getElementById('subscribe').style.display='block';
			}else{
				document.getElementById('get_back_soon').innerHTML="Please Enter a Valid E-Mail Id";
				document.getElementById('thank_you_message').style.display='none';
				document.getElementById('subscribe').style.display='block';
			}			
		}
		
		function ValidateEmail(inputText){
			var mailformat = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;
			if(inputText.match(mailformat)){				
				return true;
			}
			else{
				return false;
			}
		}
	  </script>
    <!-- END About/Intro Menu -->
    </div>

  <!-- END GRID -->
  </div>

<!-- END w3-content -->
</div>

<!-- Subscribe Modal -->
<div id="subscribe" class="w3-modal w3-animate-opacity">
  <div class="w3-modal-content" style="padding:32px">
    <div class="w3-container w3-white">
      <i onclick="document.getElementById('subscribe').style.display='none'" class="fa fa-remove w3-transparent w3-button w3-xlarge w3-right"></i>
      <h2 class="w3-wide"><span class="w3-text-red">SUBSCRIBE</span></h2>
      <p id="get_back_soon">We will get back to you soon !!!</p>
      <p id="thank_you_message">Thank you For Subscribing</p>      
    </div>
  </div>
</div>

<!-- Footer -->
<footer class="w3-container w3-dark-grey" style="padding:32px">
  <a href="#" class="w3-button w3-black w3-padding-large w3-margin-bottom"><i class="fa fa-arrow-up w3-margin-right"></i>To the top</a>
  <p>abhishekmashetty117@gmail.com </p>
  <p>Abhishek Mashetty &copy 2019 </p>
</footer>

<script>
// Toggle between hiding and showing blog replies/comments


function likeFunction(x) {
  x.style.fontWeight = "bold";
  x.innerHTML = "✓ Liked";
}
</script>

</body>
		<!-- Paste this code after body tag -->
		<div class="se-pre-con"></div>
		<!-- Ends -->
</html>

